import asyncio
import json
from pathlib import Path
from src.microanalyst.agents.trace_system import trace_collector
from src.microanalyst.agents.agent_coordinator import AgentCoordinator
import os
import shutil

# Set PYTHONPATH
os.environ["PYTHONPATH"] = os.getcwd()

async def test_trace_system():
    print("Testing Agent Trace System...")
    
    # 1. Test Manual Tracing
    print("\n[Scenario: Manual Trace Collection]")
    trace_id = "test_manual_trace"
    trace_collector.start_trace(trace_id, "Test Manual Objective", "test_agent")
    
    trace_collector.record_event(
        trace_id, "reasoning_step", "Thinking about market regime",
        reasoning="Bullish structures are holding on high timeframes",
        confidence=0.88,
        role="analyst"
    )
    
    trace_collector.record_event(
        trace_id, "tool_call", "Fetching price data",
        inputs={"symbol": "BTC/USD"},
        outputs={"price": 98500},
        role="data_collector"
    )
    
    trace_collector.complete_trace(trace_id, {"final_call": "long"})
    
    # Verify file exists
    trace_files = list(Path("traces").glob(f"{trace_id}_*.json"))
    print(f"Trace file generated: {len(trace_files) > 0}")
    assert len(trace_files) > 0
    
    # Verify Content
    with open(trace_files[0]) as f:
        data = json.load(f)
        assert data['status'] == "completed"
        assert len(data['events']) == 2
        print(f"Events captured: {len(data['events'])}")

    # 2. Test Integrated Tracing in Coordinator
    print("\n[Scenario: Integrated Coordinator Tracing]")
    coordinator = AgentCoordinator()
    results = await coordinator.execute_multi_agent_workflow(
        "technical_only",
        {"lookback_days": 14}
    )
    
    # Find the trace generated by coordinator
    # It starts with trace_technical_only_
    coord_traces = list(Path("traces").glob("trace_technical_only_*.json"))
    print(f"Coordinator trace generated: {len(coord_traces) > 0}")
    assert len(coord_traces) > 0
    
    # 3. Test Explainability Report
    print("\n[Scenario: Explainability Report Generation]")
    report = trace_collector.generate_explainability_report(trace_id)
    print("Generated Report Preview:")
    print("-" * 30)
    print("\n".join(report.split("\n")[:15]))
    print("-" * 30)
    
    assert "# Agent Reasoning Explanation" in report
    assert "Thinking about market regime" in report
    assert "Fetching price data" in report

    print("\nTrace System verification passed!")

if __name__ == "__main__":
    # Clean traces dir for test
    if Path("traces").exists():
        for f in Path("traces").glob("test_manual_trace_*.json"): f.unlink()
        for f in Path("traces").glob("trace_technical_only_*.json"): f.unlink()
        
    asyncio.run(test_trace_system())
