"""FastAPI route handlers for the Antigravity Swarm API.

This module defines the REST API endpoints for accessing market thesis data,
health status, and real-time log streaming.
"""

from fastapi import APIRouter, Request
from sse_starlette.sse import EventSourceResponse
import asyncio
import json
import os
from pathlib import Path
from typing import Dict, Any, Union
from src.microanalyst.server.schemas import HealthResponse, ThesisResponse


router = APIRouter()

# Paths
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
DATA_DIR = PROJECT_ROOT / "data_exports"
LOG_FILE = PROJECT_ROOT / "logs" / "async_retrieval.log"
THESIS_FILE = DATA_DIR / "latest_thesis.json"

@router.get("/health", response_model=HealthResponse)
async def health_check():
    """Health check endpoint for API server status monitoring.
    
    Returns the operational status of the Antigravity Swarm API server.
    Used by monitoring tools and load balancers to verify server availability.
    
    Returns:
        HealthResponse: Dictionary containing:
            - status (str): Current server status, typically "online"
            - service (str): Service identifier name
    
    Example:
        >>> response = await health_check()
        >>> response["status"]
        'online'
    """
    return {"status": "online", "service": "Antigravity Swarm API"}

@router.get("/api/v1/latest/thesis", response_model=Union[ThesisResponse, Dict[str, Any]])
async def get_latest_thesis():
    """Retrieve the most recent market thesis from the agent swarm.
    
    Reads the latest thesis JSON file generated by the adversarial agent debate
    swarm. The thesis contains a synthesized market decision (BUY/SELL/HOLD),
    confidence scoring, allocation recommendations, and multi-perspective analysis
    from specialized agents (Retail, Whale, Macro, Institutional).
    
    Returns:
        ThesisResponse | Dict[str, Any]: If thesis exists, returns ThesisResponse with:
            - decision (str): Trading action (BUY, SELL, or HOLD)
            - confidence (float): Confidence score 0.0-1.0
            - allocation_pct (float): Recommended portfolio allocation percentage
            - reasoning (str): Synthesized decision rationale
            - bull_case (str, optional): Retail analyst's bullish perspective
            - bear_case (str, optional): Whale analyst's bearish perspective
            - macro_thesis (str, optional): Macro analyst's correlation analysis
            - logs (List[str]): System logs from the debate process
        
        If thesis not ready, returns:
            - status (str): "waiting_for_swarm"
            - thesis (None): Null value indicating no thesis available
    
    Raises:
        Returns dict with "error" key if file read fails.
    
    Example:
        >>> thesis = await get_latest_thesis()
        >>> thesis["decision"]
        'BUY'
        >>> thesis["confidence"]
        0.85
    
    Note:
        Thesis file location: PROJECT_ROOT/data_exports/latest_thesis.json
        File is updated asynchronously by the agent coordinator workflow.
    """
    if not THESIS_FILE.exists():
        return {"status": "waiting_for_swarm", "thesis": None}
    
    try:
        with open(THESIS_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        return data
    except Exception as e:
        return {"error": str(e)}

@router.get("/api/v1/stream/logs")
async def message_stream(request: Request):
    """Stream real-time log updates via Server-Sent Events (SSE).
    
    Establishes an SSE connection to continuously stream new log entries from
    the async retrieval pipeline. Implements a tail-following mechanism that
    monitors the log file and pushes new lines to connected clients.
    
    Args:
        request (Request): FastAPI request object for connection management.
            Used to detect client disconnection and terminate the stream.
    
    Returns:
        EventSourceResponse: SSE stream yielding log events with format:
            - event: "log"
            - data: Log line content (string)
    
    Behavior:
        - Seeks to end of log file on connection (only new logs streamed)
        - Polls every 500ms for new log lines
        - Automatically closes stream when client disconnects
        - Yields "Log file not found" message if log file doesn't exist
    
    Example Client Usage (JavaScript):
        >>> const eventSource = new EventSource('/api/v1/stream/logs');
        >>> eventSource.addEventListener('log', (event) => {
        ...     console.log('New log:', event.data);
        ... });
    
    Note:
        Log file location: PROJECT_ROOT/logs/async_retrieval.log
        This is a long-lived connection; ensure proper client cleanup.
    """
    
    async def event_generator():
        """Internal async generator for SSE event production.
        
        Yields:
            Dict[str, str]: SSE event dictionaries with 'event' and 'data' keys.
        """
        # Simple tail implementation
        if not LOG_FILE.exists():
            yield {"event": "log", "data": "Log file not found."}
            return

        with open(LOG_FILE, "r", encoding="utf-8") as f:
            # Move to end
            f.seek(0, os.SEEK_END)
            
            while True:
                if await request.is_disconnected():
                    break
                    
                line = f.readline()
                if line:
                    yield {"event": "log", "data": line.strip()}
                else:
                    await asyncio.sleep(0.5)

    return EventSourceResponse(event_generator())
